### ISSUE TITLE
There is no output if case of error

### ISSUE THREAD

**Issue by okgolove** [dmlittle/scenery#13]
I have a module which setup prometheus with grafana and some dashboards. There are some values ${DS_PROMETHEUS} in dashboard's json. You have to replace ${} with $${} to escape it.
If you don't do it you get next error:

> Error: Error refreshing state: 1 error(s) occurred:
> 
> * module.monitoring.data.template_file.grafana: 1 error(s) occurred:
> 
> * module.monitoring.data.template_file.grafana: data.template_file.grafana: failed to render : 10282:34: unknown variable accessed: DS_PROMETHEUS

The problem is scenery doesn't show this error and you are not able to understand what's happened.

You can fix it using redirect stderr > stdout:

```terraform plan 2>&1 | scenery```

Can scenery catch stderr as well?

**Comment by dmlittle** [comment]
@okgolove thanks for reporting this issue. You're right that we currently don't capture stderr (although it's certainly possible). I'll look into adding functionality for this this weekend. 

Just to confirm, these are `terraform plan` errors that are currently being swallowed and discarded by `scenery` (because they're both being piped). Piping stderr through scenery without any modifications would solve this issue, right?

**Comment by okgolove** [comment]
@dmlittle as far I understood your question it's possible to get stderr using stderr to stdour redirection with scenery. If you don't do it `2>&1` you don't get error message.

**Comment by dmlittle** [comment]
Scenery is not actively maintained and the repo will be archived momentarily. I no longer have the time to maintain this tool nor do I think it should be kept being used as Terraform 0.11 has been deprecated for over a year now (scenery can only parse Terraform 0.11 plan outputs). Terraform 0.14 has some plan output changes as well as introduced the concept of concise diff plan outputs which does most of what scenery currently does. 

If you'd like to add new functionality as you cannot upgrade your terraform version feel free you fork the repo.
