### ISSUE TITLE
Init output still appearing

### ISSUE THREAD

**Issue by Jonnymcc** [dmlittle/scenery#35]
terragrunt version **v0.18.3**
Terraform **v0.11.13**

```
/usr/local/bin/terragrunt plan --terragrunt-tfpath /usr/local/bin/terraform  -out plan.json | scenery -n
[terragrunt] [/Users/jonathanmc/***/***] 2019/07/16 12:17:38 Running command: /usr/local/bin/terraform --version
[terragrunt] 2019/07/16 12:17:38 Reading Terragrunt config file at /Users/jonathanmc/***/***
[terragrunt] [/Users/jonathanmc/***/***] 2019/07/16 12:17:38 Initializing remote state for the s3 backend
...
etc...
```

**Comment by dmlittle** [comment]
@Jonnymcc thanks for opening an issue. Currently scenery doesn't officially support Terragrunt since I don't use it and have no experience with it. That being said I'm not opposed to adding this functionality, If you feel comfortable adding it I'll gladly accept a PR for it!

Stripping these outputs would likely happen in the `preprocessPlan` function [here](https://github.com/dmlittle/scenery/blob/13ffc24631751185673cf3c98457830ce1caa8ff/pkg/parser/parser.go#L128-L180).

**Comment by dmlittle** [comment]
Scenery is not actively maintained and the repo will be archived momentarily. I no longer have the time to maintain this tool nor do I think it should be kept being used as Terraform 0.11 has been deprecated for over a year now (scenery can only parse Terraform 0.11 plan outputs). Terraform 0.14 has some plan output changes as well as introduced the concept of concise diff plan outputs which does most of what scenery currently does. 

If you'd like to add new functionality as you cannot upgrade your terraform version feel free you fork the repo.
